apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MYSQL_USER: "CHANGE_ME"
  MYSQL_PASSWORD: "CHANGE_ME"
  MYSQL_DATABASE: "CHANGE_ME"
  MYSQL_ROOT_PASSWORD: "CHANGE_ME"
