pipeline {
    agent any // Run on any available agent

    stages {
        stage('Clone repository') {
            steps {
                git branch: 'elbit/jenkinsdec26', url: 'https://github.com/yanivomc/devopshift-welcome.git' // Replace with your repository URL
            }
        }

        stage('InstallApp') {
            steps {
                //echo "pip install"
                pip install -r requirements.txt 
            }
        }
        stage('Build') {
            steps {
                echo "Javac."
            }
        }

        stage('Parallel Mock Tests') {
            parallel {
                stage('Unit Test ') {
                    steps {
                        echo "Unit Test."
                        // Add commands to execute Mock Test 1
                    }
                }
                stage('Integration Test ') {
                    steps {
                        echo "Integration Test."
                        // Add commands to execute Mock Test 2
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'This will always run regardless of the result.'
        }
        success {
            echo 'Send Mail'

        }
        failure {
            // Replace with your email-ext plugin configuration
            emailext(
                subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                body: """<p>There was a failure in the pipeline:</p>
                         <p><b>Job:</b> ${env.JOB_NAME}</p>
                         <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>
                         <p>Check console output at <a href="${env.BUILD_URL}console">here</a> to view the details.</p>""",
                recipientProviders: [culprits(), requestor(), recipientList('matros_dim@hotmail.com')]
            )
        }

    }
}
