#DOCKERFILE ADVANCED LAB
#Create app.py 

#import flask
#print('hello')
#Create req.txt file and inside write:
#flask
#Create docker file:
#Get python image
#Content of dockerfile
#FROM …
#pip install -r req.txt
#Run the app : python app.py
