apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: moose
  name: moose
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: moose
  type: ClusterIP
status:
  loadBalancer: {}
