pipeline {
    agent any // Run on any available agent

    stages {
        stage('Clone repository') {
            steps {
                git 'https://github.com/yanivomc/devopshift-welcome.git' , 'elbit/jenkinsdec26'
            }
        }

        stage('Build') {
            steps {
                sh 'echo “javac”' // Install dependencies
            }
        }

        stage('Unit Tests') {
            steps {
                sh 'python -m unittest discover' // Run unit tests
            }
        }

        stage('Parallel Tasks') {
            parallel {
                stage('Unit Test') {
                    steps {
                        sh 'echo "unit test"'
                    }
                }
                stage('Integration Test') {
                    steps {
                        sh 'echo "unit test"'
                    }
                }
            }
        }
    }

    post {
        failure {
            echo 'echo "send mail'
        }
    }
}