pipeline {
    agent any // Run on any available agent

    stages {
        stage('Clone repository') {
            steps {
                git branch: 'elbit/jenkinsdec26' , url: 'https://github.com/yanivomc/devopshift-welcome.git' 
            }
        }

        stage('Build') {
            steps {
                echo "javac"
            }
        }

        stage('Parallel Tasks') {
            parallel {
                stage('Unit Test') {
                    steps {
                        echo "unit test"
                    }
                }
                stage('Integration Test') {
                    steps {
                        echo "unit test"
                    }
                }
            }
        }
    }

    post {
        failure {
            echo 'echo "send mail"
            emailext(
                subject: "Failed pipeline: ${currentBuild.fullDisplayName}",
                body: """<p>There was a failure in the pipeline:</p>
                         <p><b>Job:</b> ${env.JOB_NAME}</p>
                         <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>
                         <p>Check console output at <a href="${env.BUILD_URL}console">here</a> to view the details.</p>""",
                recipientProviders: [culprits(), requestor(), recipientList('ron.huberfeld@gmail.com')]
            )
        }
    }
}