pipeline {
    agent any // Run on any available agent

    stages {
        stage('Clone repository') {
            steps {
                git branch: 'elbit/jenkinsdec26' , url: 'https://github.com/yanivomc/devopshift-welcome.git' 
            }
        }

        stage('Build') {
            steps {
                echo "javac"
            }
        }

        stage('Parallel Tasks') {
            parallel {
                stage('Unit Test') {
                    steps {
                        echo "unit test"
                    }
                }
                stage('Integration Test') {
                    steps {
                        echo "unit test"
                    }
                }
            }
        }
    }

    post {
        failure {
            echo 'echo "send mail'
        }
    }
}