pipeline {
    agent any // Run on any available agent

    stages {
        stage('Clone repository') {
            steps {
                git branch: 'elbit/jenkinsdec26', url: 'https://github.com/yanivomc/devopshift-welcome.git' 
            }
        }

        stage('Build') {
            steps {
                sh 'echo javac' 
            }
        }


        stage('Parallel Mock Tests') {
            parallel {
                stage('unitest') {
                    steps {

                        sh 'echo unitest' // This test fails
                }
                stage('Integration test') {

                                sh 'echo Integration test' // This test fails

                }
            }
        }
    }

    post {
        failure {
            script {
                // Send email notification only on failure
                emailext subject: "Failed: ${currentBuild.fullDisplayName}",
                          body: "The build '${currentBuild.fullDisplayName}' has failed. Please check the Jenkins logs for more information.",
                          to: 'roysadan@gmail.com',
                          mimeType: 'text/html'
            }
        }
    }
}