pipeline {
    agent any // Run on any available agent

    stages {
        stage('Clone repository') {
            steps {
                git 'https://github.com/yanivomc/devopshift-welcome.git BRANCH( elbit/jenkinsdec26 )' // Replace with your repository URL
            }
        }

        stage('Build') {
            steps {
                echo “javac” // Install dependencies
            }
        }

        stage('Parallel tasks') {
            parallel {
                stage('Unit test') {
                    steps {
                        sh 'echo "unit test"' // Replace with actual test command
                        // Add commands to execute Mock Test 1
                    }
                }
                stage('Integration test') {
                    steps {
                        sh 'echo "integration test"' // Replace with actual test command
                        // Add commands to execute Mock Test 2
                    }
                }                
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed.'
        }
    }
}