pipeline {
    agent any // Run on any available agent

    stages {
        stage('Clone repository') {
            steps {
                git 'https://github.com/yanivomc/devopshift-welcome.git BRANCH( elbit/jenkinsdec26 )' // Replace with your repository URL
            }
        }

        stage('Build') {
            steps {
                echo “javac” // Install dependencies
            }
        }

        stage('Parallel tasks') {
            parallel {
                stage('Unit test') {
                    steps {
                        sh 'echo "unit test"' // Replace with actual test command
                        // Add commands to execute Mock Test 1
                    }
                }
                stage('Integration test') {
                    steps {
                        sh 'echo "integration test"' // Replace with actual test command
                        // Add commands to execute Mock Test 2
                    }
                }                
            }
        }
    }

    post {
        failure {
            // Replace with your email-ext plugin configuration
            emailext(
                subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                body: """<p>There was a failure in the pipeline:</p>
                         <p><b>Job:</b> ${env.JOB_NAME}</p>
                         <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>
                         <p>Check console output at <a href="${env.BUILD_URL}console">here</a> to view the details.</p>""",
                recipientProviders: [culprits(), requestor(), recipientList('your.email@example.com')]
            )
        }
    }
}