apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 50.0
        zipkin:
          address: jaeger-collector.istio-system.svc.cluster.local:9411
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true        
    egressGateways:
      - name: istio-egressgateway
        enabled: true
  values:
    global:
      istioNamespace: istio-system
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
          limits:
            cpu: 100m
            memory: 128Mi
